name: CI-CD Fintech

on:
  push:
    branches:
      - main

jobs:

  build:

    name: Build e Validacao

    runs-on: ubuntu-latest

    steps:

      - name: Checkout do Codigo
        uses: actions/checkout@v4

      - name: Validar Arquivos
        run: |
          echo "Arquivos encontrados:"
          ls -la

      - name: Verificar index.html
        run: |
          test -f index.html

      - name: Build Docker
        run: |
          docker build -t pagaja .

  deploy:

    name: Deploy AWS EC2

    runs-on: ubuntu-latest

    needs: build

    steps:

      - name: Deploy na EC2
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}

          script: |

            cd /home/ubuntu

            if [ ! -d devops-lab11-pagueja ]; then
              git clone https://github.com/Helinho7/devops-lab11-pagueja.git
            fi

            cd devops-lab11-pagueja

            git pull

            sudo docker stop pagaja || true
            sudo docker rm pagaja || true

            sudo docker build -t pagaja .

            sudo docker run -d \
              --name pagaja \
              -p 80:80 \
              pagaja

            sudo docker ps
