name: Deploy Fintech

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Validar Arquivos
        run: |
          echo "Pipeline executada com sucesso"
          ls -la
